### PR TITLE
Complete Testing

### PR DESCRIPTION
**Pull request by teseoch**
- [x] fix all existing test
    - [ ] contact/examples/3D/static/two-cubes.json
    - [x] contact/examples/3D/golf-ball.json
    - [x] contact/examples/3D/higher-order/golf-ball-P2.json
    - [x] contact/examples/3D/higher-order/golf-ball-P1.json
    - [x] contact/examples/2D/static/friction-slope.json
- [x] test static stokes 
- [ ] test transient stokes 
- [x] test static Navier-Stokes 
- [x] test transient Navier-Stokes 
- [ ] test transient laplace
- [ ] test transient helmolz
- [ ] test transient LinearElasticity
- [ ] test static LinearElasticity
- [ ] test transient HookeLinearElasticity
- [ ] test transient SaintVenant
- [ ] test transient MultiModels
- [ ] test static MultiModels
- [ ] test transient IncompressibleLinearElasticity
- [ ] test static IncompressibleLinearElasticity
- [ ] test transient Bilaplacian
- [ ] test static Bilaplacian
- [ ] test OperatorSplitting
- [ ] test BDF 1 2 3
- [ ] test Newmark
- [ ] test LBFGS solver

Others?

Example of the old runner:
```
./PolyFEM_bin --mesh ../data/data/contact/meshes/3D/simple/cube.msh --cmd --n_refs 1 --problem DrivenCavity --tform Stokes
./PolyFEM_bin --mesh ../data/data/contact/meshes/3D/simple/cube.msh --cmd --n_refs 1 --problem DrivenCavity --tform NavierStokes
```

Old python code: https://github.com/polyfem/polyfem/blob/main/tests/test_runners.py

### CODE REVIEW

**Comment by teseoch** [comment]
Golf ball test is using a lot of memory

**Comment by teseoch** [comment]
Currently failing:
- [ ]
contact/examples/3D/higher-order/golf-ball-P2.json
Not Allowed appending JSON!! Add a * to the beginning of filename.

- [ ]
contact/examples/3D/golf-ball.json
std::bad_alloc

- [ ]
contact/examples/3D/friction/armadillo-roller.json
Subprocess killed***Exception

- [ ]
Processing multi-material/stretch-cubes.json
No valid rules in this list:

- [ ]
contact/examples/2D/initial_angular_velocity.json
Violating Authenticate err_h1

- [ ]
contact/examples/3D/higher-order/golf-ball-P2.json
 Not Allowed appending JSON!! Add a * to the beginning of filename.

**Comment by zfergus** [comment]
* [ ] `multi-material/stretch-cubes.json` now fails because of #95

**Comment by zfergus** [comment]
`multi-material/stretch-cubes.json` works now.

**Comment by teseoch** [comment]
new failure `contact/examples/3D/static/two-cubes.json`

**Comment by zfergus** [comment]
* [ ] LBFGS solver

**Comment by zfergus** [comment]
Current failing tests are
* [ ] contact/examples/3D/static/two-cubes.json
* [ ] contact/examples/3D/golf-ball.json
* [ ] contact/examples/3D/higher-order/golf-ball-P2.json
* [ ] contact/examples/3D/higher-order/golf-ball-P1.json
* [ ] contact/examples/2D/static/friction-slope.json

**Comment by teseoch** [comment]
- [ ] test quad/hex
- [ ] test spline
- [ ] test polygons

**Comment by teseoch** [comment]
- [ ] `contact/examples/2D/static/friction-slope.json` takes random amount of time

**Pull request closed without merging**
