### PR TITLE
append ncmesh

### PR DESCRIPTION
**Pull request by teseoch**

### CODE REVIEW

**Comment by teseoch** [comment]
can you remove the . from the ncmesh test?

**Comment by zfergus** [comment]
> can you remove the . from the ncmesh test?

done

**Comment by zfergus** [comment]
Seems like this function is still not implemented in NCMesh3D:
```
void set_point(const int global_index, const RowVectorNd &p) override { throw std::runtime_error("Not implemented"); }
```

**Comment by zfergus** [comment]
I think we can merge this now.

**Pull request merged**
