### PR TITLE
fix bug for mooney rivlin in 2D

### PR DESCRIPTION
**Pull request by Huangzizhou**
The old 2D Mooney-Rivlin was wrongly inferred from the 3D version -- it is not zero at rest pose and can be negative. The fixed version now is by assuming the deformation gradient is 0,0,1 in the 3rd dimension.

### CODE REVIEW

**Comment by Huangzizhou** [comment]
As suggested by @arvigj , the $(J-1)^2$ is replaced by $\log^2J$ so that the energy tends to infinity as $J$ tends to zero, i.e. close to a singular element.

**Comment by arvigj** [comment]
Did you remove the calls to `first_invariant` and `second_invariant` for performance reasons? Also I think that the 3 parameter model here is the same as the 2 parameter one with `c3 = 0`, can we remove the 2 parameter model file?

**Comment by Huangzizhou** [comment]
@teseoch Do you agree with the changes and removing the 2 parameter mooney-Rivlin as Arvi suggested?

**Comment by Huangzizhou** [comment]
put back $J-1$ as discussed

**Comment by teseoch** [comment]
I think we should keep all of them. this looks like a different model now

**Comment by teseoch** [comment]
https://help.febio.org/docs/FEBioTheory-4-5/TM45-Subsection-5.3.1.html this is where it came form

**Comment by Huangzizhou** [comment]
It's exactly the same as before in 3D, the changes are to avoid some repeated computation. Yeah, they don't have a 2D version, the old 2D version is likely wrong, the new one is by assuming def grad is 0,0,1 in the 3rd dimension.

**Pull request merged**
